name: Docker image build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build Docker image
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          tag=$(echo ${GITHUB_REF} | sed -e 's#^refs/heads/##')
          echo "tag: ${tag}"
          image_name="docker.pkg.github.com/${GITHUB_REPOSITORY}/sample"
          echo "image_name: ${image_name}"

          docker build --tag ${image_name}:${tag} .
